import PDFDocument from "pdfkit";
import { formatAmount, formatDate } from "./formatters";

export interface InvoicePDFData {
  invoiceCode: string;
  projectName: string;
  clientPhone: string;
  freelancerName: string;
  freelancerAccountNumber?: string | null;
  freelancerBank?: string | null;
  amount: number;
  currency: string;
  dueDate: Date;
  createdAt: Date;
}

export function generateInvoicePDF(data: InvoicePDFData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.fontSize(24).font("Helvetica-Bold").text("PACTAI", 50, 50);
    doc.fontSize(10).font("Helvetica").fillColor("#666666")
      .text("Financial Workflow Agent", 50, 80);

    // Title
    doc.fillColor("#000000").fontSize(18).font("Helvetica-Bold")
      .text("INVOICE", 400, 50, { align: "right" });
    doc.fontSize(11).font("Helvetica").fillColor("#333333")
      .text(data.invoiceCode, 400, 75, { align: "right" });

    // Divider
    doc.moveTo(50, 110).lineTo(545, 110).strokeColor("#cccccc").stroke();

    // Dates
    doc.fontSize(10).fillColor("#555555")
      .text(`Issue Date: ${formatDate(data.createdAt)}`, 50, 125)
      .text(`Due Date:   ${formatDate(data.dueDate)}`, 50, 140);

    // Bill To
    doc.fontSize(11).font("Helvetica-Bold").fillColor("#000000")
      .text("BILL TO", 50, 175);
    doc.fontSize(10).font("Helvetica").fillColor("#333333")
      .text(`Client: +${data.clientPhone}`, 50, 192);

    // From
    doc.fontSize(11).font("Helvetica-Bold").fillColor("#000000")
      .text("FROM", 300, 175);
    doc.fontSize(10).font("Helvetica").fillColor("#333333")
      .text(data.freelancerName, 300, 192);
    if (data.freelancerAccountNumber && data.freelancerBank) {
      doc.text(`Account: ${data.freelancerAccountNumber}`, 300, 207)
         .text(`Bank: ${data.freelancerBank}`, 300, 222);
    }

    // Project table
    doc.moveTo(50, 260).lineTo(545, 260).strokeColor("#cccccc").stroke();
    doc.fontSize(10).font("Helvetica-Bold").fillColor("#555555")
      .text("DESCRIPTION", 50, 270)
      .text("AMOUNT", 450, 270, { align: "right", width: 95 });
    doc.moveTo(50, 288).lineTo(545, 288).strokeColor("#cccccc").stroke();

    doc.fontSize(11).font("Helvetica").fillColor("#000000")
      .text(data.projectName, 50, 300)
      .text(formatAmount(data.amount, data.currency), 450, 300, { align: "right", width: 95 });

    doc.moveTo(50, 325).lineTo(545, 325).strokeColor("#cccccc").stroke();

    // Total
    doc.fontSize(13).font("Helvetica-Bold")
      .text("TOTAL", 350, 340)
      .text(formatAmount(data.amount, data.currency), 450, 340, { align: "right", width: 95 });

    // Footer
    doc.fontSize(9).font("Helvetica").fillColor("#999999")
      .text("Generated by Pactai — Powered by AI financial workflows.", 50, 700, { align: "center" });

    doc.end();
  });
}
